### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/api/v1/students

###
GET http://localhost:8080/api/v1/students/0


###
POST http://localhost:8080/api/v1/students/update/1
Content-Type: application/json

{
  "id": 1,
  "name": "qeqweq",
  "email": "qesafas",
  "age": 3
}

###
POST http://localhost:8080/api/v1/students/delete/-1

