spring.application.name=StudentManagement

#spring.datasource.url=jdbc:sqlite:student.db
#spring.datasource.driver-class-name=org.sqlite.JDBC
#
#spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#
#spring.application.name=WebTest
spring.datasource.url=jdbc:postgresql://localhost:5332/students_db
spring.datasource.username=ax0lotl79
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
